version: 2.1

jobs:
  run-postman-tests:
    docker:
      - image: postman/newman:alpine
    steps:
      - checkout
      - run:
          name: Run Postman tests
          command: |
            newman run ./postman/List_tests_Home_work_3.postman_collection.json \
              -e ./postman/Env_for_HW_3.postman_environment.json \
              --reporters cli,html \
              --reporter-html-export postman_report.html

workflows:
  version: 2
  run-tests:
    jobs:
      - run-postman-tests
